# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=80)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
